#data_base_dir: /home/tran/dev/partial_spoof/tedx_test
data_base_dir: /gs/bs/tgh-25IAC/ud03523/WORK/project-partialspoof/data/other_testsets
trn_list: /gs/bs/tgh-25IAC/ud03523/WORK/project-partialspoof/data/other_testsets/mls_coded/mixed_csv/v1/trn.csv
val_list: /gs/bs/tgh-25IAC/ud03523/WORK/project-partialspoof/data/other_testsets/mls_coded/mixed_csv/v1/val.csv
eval_list: /gs/bs/tgh-25IAC/ud03523/WORK/project-partialspoof/data/other_testsets/mls_coded/csv/v1/eval.csv
eval_set_name: mls_coded
train_ratio: 0.8
text_max_length: 1000
learning_rate: 0.0001
weight_decay: 0.01
adam_epsilon: 1e-8
warmup_steps: 2
batch_size: 16
num_worker: 2
num_train_epochs: 15
gradient_accumulation_steps: 1
sample_rate: 16000
train_name: resnet152
train_id: '0'
checkpoint: loss