#
data_base_dir: ${WORK}/data/other_testsets/llamapartialspoof
trn_list: ${WORK}/data/other_testsets/llamapartialspoof/trn_60k.csv
val_list: ${WORK}/data/other_testsets/llamapartialspoof/val_4k.csv
eval_list: ${WORK}/data/other_testsets/llamapartialspoof/../../protocols_merged/eval_new.csv
eval_set_name: tedx
train_ratio: 0.8
text_max_length: 1000
learning_rate: 0.0001
weight_decay: 0.01
adam_epsilon: 1e-8
warmup_steps: 2
batch_size: 16
num_worker: 2
num_train_epochs: 30
gradient_accumulation_steps: 1
sample_rate: 16000
train_name: resnet152
train_id: '0'
checkpoint: loss