# based on loss_cfg12.yaml
data_base_dir: /gs/bs/tgh-25IAC/ud03523/WORK/project-partialspoof/partial_spoof_to_zip/tedx_test
eval_set_name: tedx
model_name: large
lang: fr
learning_rate: 0.00001
weight_decay: 0.01
adam_epsilon: 1e-8
warmup_steps: 2
batch_size: 8
num_worker: 4
num_train_epochs: 20
gradient_accumulation_steps: 1
sample_rate: 16000
train_ratio: 0.8
vocoding_label: "!!!!!!"
finetune_encoder: true
weight_vocoded_token: 1.0
weight_other_token: 0.1
trim_leading_pad: 4
use_rawboost: true
rawboost_config:
  # Rawboost algorithms: 
  # 0: No augmentation, 1: LnL_convolutive_noise, 2: ISD_additive_noise,
  # 3: SSI_additive_noise, 4: 1+2+3, 5: 1+2, 6: 1+3, 7: 2+3, 8: 1+3
  algo: 5 

  # LnL_convolutive_noise parameters
  LnL_convolutive_noise:
    nBands: 5       # Number of notch filters
    minF: 20        # Minimum centre frequency [Hz] of notch filter
    maxF: 8000      # Maximum centre frequency [Hz] (<sr/2) of notch filter
    minBW: 100      # Minimum width [Hz] of filter
    maxBW: 1000     # Maximum width [Hz] of filter
    minCoeff: 10    # Minimum filter coefficients
    maxCoeff: 100   # Maximum filter coefficients
    minG: 0         # Minimum gain factor of linear component
    maxG: 0         # Maximum gain factor of linear component
    minBiasLinNonLin: 5  # Minimum gain difference between linear and non-linear components
    maxBiasLinNonLin: 20 # Maximum gain difference between linear and non-linear components
    N_f: 5          # Order of the (non-)linearity where N_f=1 refers only to linear components

  # ISD_additive_noise parameters
  ISD_additive_noise:
    P: 10       # Maximum number of uniformly distributed samples in [%]
    g_sd: 2     # Gain parameters > 0

  # SSI_additive_noise parameters
  SSI_additive_noise:
    SNRmin: 10  # Minimum SNR value for coloured additive noise