data_base_dir: /gs/bs/tgh-25IAC/ud03523/WORK/project-partialspoof/data
trn_list: /gs/bs/tgh-25IAC/ud03523/WORK/project-partialspoof/data/protocols/replacement_fr_hn_sinc_nsf_hifi_trn.csv,/gs/bs/tgh-25IAC/ud03523/WORK/project-partialspoof/data/protocols/replacement_fr_hn_sinc_nsf_hifi_val.csv
val_list: /gs/bs/tgh-25IAC/ud03523/WORK/project-partialspoof/data/protocols/replacement_fr_hn_sinc_nsf_hifi_eval.csv
eval_list: /gs/bs/tgh-25IAC/ud03523/WORK/project-partialspoof/data/protocols/replacement_fr_hn_sinc_nsf_hifi_eval.csv
#data_base_dir: /gs/bs/tgh-25IAC/ud03523/WORK/project-partialspoof/partial_spoof_to_zip/tedx_test
model_name: large
lang: fr
learning_rate: 0.00001
weight_decay: 0.01
adam_epsilon: 1e-8
warmup_steps: 2
batch_size: 8
num_worker: 4
num_train_epochs: 20
gradient_accumulation_steps: 1
sample_rate: 16000
train_ratio: 0.8
vocoding_label: "!!!!!!"
finetune_encoder: true
weight_vocoded_token: 1.0
weight_other_token: 0.8