# 
data_base_dir: /gs/bs/tgh-25IAC/ud03523/WORK/project-partialspoof/data
trn_list: /gs/bs/tgh-25IAC/ud03523/WORK/project-partialspoof/data/protocols_v5/trn.csv
val_list: /gs/bs/tgh-25IAC/ud03523/WORK/project-partialspoof/data/protocols_v5/val.csv
eval_list: /gs/bs/tgh-25IAC/ud03523/WORK/project-partialspoof/data/protocols_merged/eval_new.csv
eval_set_name: tedx
model_name: large
# large is a multi-lingual, just set fr for convenience
lang: fr
learning_rate: 0.00001
weight_decay: 0.01
adam_epsilon: 1e-8
warmup_steps: 2
batch_size: 8
num_worker: 4
num_train_epochs: 10
gradient_accumulation_steps: 1
# working sampling rate of the model
sample_rate: 16000
finetune_encoder: true
weight_vocoded_token: 1.0
weight_other_token: 1.0
trim_leading_pad: 4
checkpoint: loss